## create game
POST {{host}}/api/game
Content-Type: application/json
Authorization: Bearer {{admin-token}}

{
  "name": "hyldajksldf",
  "price": 1000,
  "description": "Nice game"
}

###
POST {{host}}/api/game
Content-Type: application/json
Authorization: Bearer {{admin-token}}

{
  "name": "lol",
  "price": 0,
  "description": "Nice game"
}

###
POST {{host}}/api/game
Content-Type: application/json
Authorization: Bearer {{admin-token}}

{
  "name": "nba2k21",
  "price": 16,
  "description": "Nice game"
}

###

#create game version

POST {{host}}/api/game/1/version
Content-Type: application/json
Authorization: Bearer {{admin-token}}

{
  "gameId": 1,
  "name": "v1.1",
  "url": "https://www.google.com/"
}

###

GET {{host}}/api/game/1

###

GET {{host}}/api/game/1/version/v1.1

###

PUT {{host}}/api/game/1
Content-Type: application/json
Authorization: Bearer {{admin-token}}

{
  "gameId": 1,
  "description": "Cool game"
}

###

GET {{host}}/api/games/

###

GET {{host}}/api/games/?order=publishDate

###

GET {{host}}/api/games/recommend/

### upload game image

POST {{host}}/api/game/1/image
Authorization: Bearer {{admin-token}}
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="FullSize"; filename="img_full.jpg"

< ../../../img_full.jpg

--WebAppBoundary
Content-Disposition: form-data; name="CardSize"; filename="img_card.jpg"

< ../../../img_card.jpg
--WebAppBoundary--

###
