# success
GET {{host}}/api/save/test001/1
Authorization: Bearer {{test001-token}}
#

###

# Permission denied, user not own the game
GET {{host}}/api/save/test001/2
Authorization: Bearer {{test001-token}}

###

# Permission denied, please login
GET {{host}}/api/save/test002/1

###

POST {{host}}/api/save/test001/1
Authorization: Bearer {{test001-token}}
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="upload"; filename="save1.txt"

< ../.././storage/store/bfd71a0c-466a-4da1-b3bd-b6fdbed65805
--WebAppBoundary--


###

# "success": true
GET {{host}}/api/save/test001/1/test001-1/delete
Authorization: Bearer {{test001-token}}


###


GET {{host}}/api/save/test001/1/save333/delete
Authorization: Bearer {{test001-token}}


###


GET {{host}}/api/save/test001/1/test001-1
Authorization: Bearer {{test001-token}}

###

