# create game
POST {{host}}/api/game
Content-Type: application/json
Authorization: Bearer {{admin-token}}

{
  "name": "TestGame3432",
  "price": 1000,
  "introduction": "nice",
  "description": "Nice game"
}

###

GET {{host}}/api/gameKey/1709958556112275173779206261496011538612088445701588374628117680877353884357

###

GET {{host}}/api/key/1
Authorization: Bearer {{admin-token}}

###
#create game version

POST {{host}}/api/game/10/version
Content-Type: application/json
Authorization: Bearer {{admin-token}}

{
  "name": "v1.0",
  "url": "c678f433-0a14-40c2-8437-99af8dc0bd1c"
}

###

GET {{host}}/api/game/1

###

GET {{host}}/api/game/10/profile

###

GET {{host}}/api/game/10/detail

###

GET {{host}}/api/game/10/version/v1.1

###

GET {{host}}/api/game/1/version

###

PUT {{host}}/api/game/10
Content-Type: application/json
Authorization: Bearer {{admin-token}}

{
  "game": {
    "gameId": 10,
    "name": "2048",
    "price": 0,
    "publishDate": "2020-03-19T00:00:01.000Z",
    "author": "admin",
    "introduction": "《2048》的任务是在一个网格上滑动小方块来进行组合，直到形成一个带有有数字2048的方块。",
    "description": "test edit"
  }
}

###

GET {{host}}/api/games/

###

GET {{host}}/api/games/?order=publishDate

###

GET {{host}}/api/games/recommend/

### upload game image

POST {{host}}/api/game/10/image
Authorization: Bearer {{admin-token}}
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="FullSize"; filename="img_full.jpg"

< ../../../img_full.jpg

--WebAppBoundary
Content-Disposition: form-data; name="CardSize"; filename="img_card.jpg"

< ../../../img_card.jpg
--WebAppBoundary--

###

POST {{host}}/api/game/10/tag
Content-Type: application/json
Authorization: Bearer {{admin-token}}

{
  "tag": "冒险"
}

###

GET {{host}}/api/game/10/tags

###

GET {{host}}/api/tags

###

GET {{host}}/api/games/tags?tag=冒险&tag=动作

###


POST {{host}}/api/game/10/upload
Authorization: Bearer {{admin-token}}
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="upload"; filename="game.txt"

< ../../../storage/store/c678f433-0a14-40c2-8437-99af8dc0bd1c
--WebAppBoundary--

###

GET {{host}}/api/game/10/version/v1.0/download
Authorization: Bearer {{admin-token}}

###
