POST {{host}}/api/store
Content-Type: multipart/form-data; boundary=WebAppBoundary
Authorization: Bearer {{admin-token}}

--WebAppBoundary
Content-Disposition: form-data; name="default avatar"; filename="default.jpg"
Content-Type: image/jpg

< ../../main/resources/default.jpg
--WebAppBoundary--

###
POST {{host}}/api/store
Content-Type: multipart/form-data; boundary=WebAppBoundary
Authorization: Bearer {{admin-token}}

--WebAppBoundary
Content-Disposition: form-data; name="whatever"; filename="database_config.json"
Content-Type: text/plain

< ../../main/resources/database_config.json
--WebAppBoundary--

###
